version: 2

jobs:
  build:
    docker:
      - image: swift:4.1
      - image: circleci/postgres:9.5

    environment:
      POSTGRES_DB: circle_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
      DATABASE_PORT: 5432

    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
