version: 2

jobs:
  build:
    docker:
      - image: swift:4.1
      - image: circleci/postgres:9.5

    environment:
      DATABASE_URL: postgres://root:@127.0.0.1:5432/circle_test

    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
