version: 2

jobs:
  build:
    docker:
      - image: swift:4.1
      - image: circleci/postgres:9.5

    environment:
      POSTGRES_DB: vapor-ci
      POSTGRES_USER: vapor-ci-user
      POSTGRES_PASSWORD: vapor-ci-password

    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
          environment:
            DATABASE_DB: vapor-ci
            DATABASE_USER: vapor-ci-user
            DATABASE_PASSWORD: vapor-ci-password
            DATABASE_PORT: 5432
